### ISSUE TITLE
need add theme(legend.position="none") with ggplot2 plot

### ISSUE THREAD

**Issue by wangjiaxuan666** [GuangchuangYu/hexSticker#117]
```
require(ggplot2)
library(hexSticker)
ggplot(dat, aes(x = x, y = y)) +
  geom_polygon(aes(fill = id, group = id)) +
  geom_point(aes(x = 3.25-0.5,y = 4.5),color =back_color,size = 6) +
  geom_point(aes(x = 3.25+0.5,y = 4.5),color =back_color,size = 6) +
  scale_fill_manual(values = xbox::need_colors("two5")) ->p
p <- p + theme_void() + theme_transparent() + theme(legend.position="none")
```
 I use  ggplot2 to make the back plot of hexSticker, but if i want dispaly the legend , it work only when  `+ theme(legend.position="none")` ,  why not add the function to theme_transparent() or new function. 

I feel apologetic if the problem only occurs on me

> devtools::session_info()
- Session info -------------------------------------------------
 setting  value                         
 version  R version 4.0.2 (2020-06-22)  
 os       Windows 10 x64                
 system   x86_64, mingw32               
 ui       RStudio                       
 language (EN)                          
 collate  Chinese (Simplified)_China.936
 ctype    Chinese (Simplified)_China.936
 tz       Asia/Taipei                   
 date     2020-12-31                    

- Packages -----------------------------------------------------
 package      * version date       lib
 assertthat     0.2.1   2019-03-21 [1]
 backports      1.1.7   2020-05-13 [1]
 BiocGenerics   0.34.0  2020-04-27 [1]
 BiocManager    1.30.10 2019-11-16 [1]
 Biostrings     2.56.0  2020-04-27 [1]
 callr          3.4.3   2020-03-28 [1]
 cli            2.0.2   2020-02-28 [1]
 clipr          0.7.0   2019-07-23 [1]
 colorspace     2.0-0   2020-11-11 [1]
 crayon         1.3.4   2017-09-16 [1]
 datapasta      3.1.0   2020-01-17 [1]
 desc           1.2.0   2018-05-01 [1]
 devtools       2.3.1   2020-07-21 [1]
 digest         0.6.27  2020-10-24 [1]
 dplyr          1.0.1   2020-07-31 [1]
 ellipsis       0.3.1   2020-05-15 [1]
 fansi          0.4.1   2020-01-08 [1]
 farver         2.0.3   2020-01-16 [1]
 fs             1.5.0   2020-07-31 [1]
 generics       0.0.2   2018-11-29 [1]
 ggimage        0.2.8   2020-04-02 [1]
 ggplot2      * 3.3.2   2020-06-19 [1]
 ggplotify      0.0.5   2020-03-12 [1]
 glue           1.4.1   2020-05-13 [1]
 gridGraphics   0.5-1   2020-12-13 [1]
 gtable         0.3.0   2019-03-25 [1]
 hablar         0.3.0   2020-03-19 [1]
 hexbin         1.28.1  2020-02-03 [1]
 hexSticker   * 0.4.9   2020-12-05 [1]
 hms            0.5.3   2020-01-08 [1]
 httr           1.4.2   2020-07-20 [1]
 IRanges        2.22.2  2020-05-21 [1]
 jsonlite       1.7.0   2020-06-25 [1]
 KEGGREST       1.28.0  2020-04-27 [1]
 labeling       0.3     2014-08-23 [1]
 lattice        0.20-41 2020-04-02 [1]
 lifecycle      0.2.0   2020-03-06 [1]
 magick         2.4.0   2020-06-23 [1]
 magrittr       1.5     2014-11-22 [1]
 memoise        1.1.0   2017-04-21 [1]
 munsell        0.5.0   2018-06-12 [1]
 pillar         1.4.6   2020-07-10 [1]
 pkgbuild       1.1.0   2020-07-13 [1]
 pkgconfig      2.0.3   2019-09-22 [1]
 pkgload        1.1.0   2020-05-29 [1]
 plyr           1.8.6   2020-03-03 [1]
 png            0.1-7   2013-12-03 [1]
 prettyunits    1.1.1   2020-01-24 [1]
 processx       3.4.3   2020-07-05 [1]
 ps             1.3.4   2020-08-11 [1]
 purrr          0.3.4   2020-04-17 [1]
 qvalue         2.20.0  2020-04-27 [1]
 R6             2.4.1   2019-11-12 [1]
 ragg           0.4.0   2020-10-05 [1]
 Rcpp           1.0.5   2020-07-06 [1]
 readr          1.3.1   2018-12-21 [1]
 remotes        2.2.0   2020-07-21 [1]
 reshape2       1.4.4   2020-04-09 [1]
 rlang          0.4.9   2020-11-26 [1]
 rprojroot      1.3-2   2018-01-03 [1]
 rstudioapi     0.11    2020-02-07 [1]
 rvcheck        0.1.8   2020-03-01 [1]
 S4Vectors      0.26.1  2020-05-16 [1]
 scales         1.1.1   2020-05-11 [1]
 sessioninfo    1.1.1   2018-11-05 [1]
 showtext       0.9     2020-08-13 [1]
 showtextdb     3.0     2020-06-04 [1]
 stringi        1.4.6   2020-02-17 [1]
 stringr        1.4.0   2019-02-10 [1]
 sysfonts       0.8.1   2020-05-08 [1]
 systemfonts    0.3.2   2020-09-29 [1]
 testthat       2.3.2   2020-03-02 [1]
 textshaping    0.2.1   2020-11-13 [1]
 tibble         3.0.3   2020-07-10 [1]
 tidyr          1.1.1   2020-07-31 [1]
 tidyselect     1.1.0   2020-05-11 [1]
 tinytex        0.25    2020-07-24 [1]
 usethis        1.6.1   2020-04-29 [1]
 vctrs          0.3.2   2020-07-15 [1]
 withr          2.2.0   2020-04-20 [1]
 xbox           0.5     2020-12-26 [1]
 xfun           0.16    2020-07-24 [1]
 XVector        0.28.0  2020-04-27 [1]
 zlibbioc       1.34.0  2020-04-27 [1]

**Comment by GuangchuangYu** [comment]
not an issue related to `theme_transparent` or `hexSticker`.

Whether use `+theme(legend.postion="none")` is depend on the user's need.
