### ISSUE TITLE
How to follow specifications?

### ISSUE THREAD

**Issue by privefl** [GuangchuangYu/hexSticker#12]
Hey, I would like to use your package to make an hex sticker for our group.
However, there are some rules of size to have coherent stickers: https://github.com/terinjokes/StickerConstructorSpec

I think, I should use the parameter `h_size` but the default value is `1.2` and we don't know the unit of this size. 

Which value should I use?

**Comment by GuangchuangYu** [comment]
see the text below the 'Examples' subtitle, <https://github.com/GuangchuangYu/hexSticker/blob/master/README.md#examples>.

**Comment by privefl** [comment]
Thanks
