### ISSUE TITLE
README.Rmd renders into .html instead of .md

### ISSUE THREAD

**Issue by rivasiker** [GuangchuangYu/hexSticker#138]
I would like to add my sticker to the examples, so I have forked the repo and edited the README.Rmd file. However, when I run `rmarkdown::render("README.Rmd")`, it creates a README.html file instead of updating README.md. Is there a way to force the knitting to .md?

**Comment by GuangchuangYu** [comment]
<https://github.com/GuangchuangYu/hexSticker/blob/master/Makefile#L13>.
