### ISSUE TITLE
aspect ratio of image subfigure not retained

### ISSUE THREAD

**Issue by cmhh** [GuangchuangYu/hexSticker#17]
It looks to me like png images etc. get stretched vertically when included?  It looks to be by a factor of 600 / 518 (or 2 / 1.73, if the linked spec is to be believed).  If I flatten the image in gimp or something, then include it, it seems to come out okay.

**Comment by cmhh** [comment]
I imagine for similar reasons, when `h_size` is greater than 1, the border gets clipped at the top an bottom of the image.  I haven't looked at the package internals yet, but it seems like the code assumes an aspect ratio of 1:1, when it is 1:0.863.

**Comment by nathaneastwood** [comment]
Flattening the image didn't work for myself. The image still appears stretched. `h_size` doesn't seem to have any effect on the image.

**Comment by cmhh** [comment]
I shouldn't have used the term 'flatten', though, since that has a particular meaning with image processing.  I more meant to change the aspect ratio in an editing program.

**Comment by gpaux** [comment]
I got the same issue, I revised a part of the code of the sticker function to get the original aspect ratio:

``` {r include=FALSE}
 if (inherits(subplot, "character")) {
    image <- png::readPNG(subplot)
    logo <-  grid::rasterGrob(image, interpolate = TRUE)
    sticker <- hex + ggplot2::annotation_custom(logo, xmin = s_x, xmax = s_x + s_width, ymin = s_y, ymax = s_y + s_height) 
  }
```

**Comment by GuangchuangYu** [comment]
now `asp` parameter supported.

**Comment by gpaux** [comment]
Thanks, nice update
