### ISSUE TITLE
Install error: error loading sysfonts

### ISSUE THREAD

**Issue by jzadra** [GuangchuangYu/hexSticker#18]
First time installing hexSticker, I get the following error and install fails:
```
install.packageas("hexSticker")
installing the source package ‘hexSticker’

trying URL 'https://cran.rstudio.com/src/contrib/hexSticker_0.4.2.tar.gz'
Content type 'application/x-gzip' length 676288 bytes (660 KB)
==================================================
downloaded 660 KB

* installing *source* package ‘hexSticker’ ...
** package ‘hexSticker’ successfully unpacked and MD5 sums checked
** R
** inst
** byte-compile and prepare package for lazy loading
Error : .onLoad failed in loadNamespace() for 'sysfonts', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so
  Reason: image not found
ERROR: lazy loading failed for package ‘hexSticker’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/hexSticker’
Warning in install.packages :
  installation of package ‘hexSticker’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/5_/l71sk6kn29z17n011g8kld5m0000gp/T/RtmpINzLug/downloaded_packages’
```

I'm using OS X 10.12.6

**Comment by GuangchuangYu** [comment]
> Error : .onLoad failed in loadNamespace() for 'sysfonts', details:

you need to re-install `sysfonts`.

**Comment by aaronrudkin** [comment]
Same error; tried `remove.packages(sysfonts); install.packages(sysfonts)`, still get same error.

**Comment by juliasilge** [comment]
I am getting this same error as well. 

I can install the sysfonts package without any problem, and can run functions like `sysfonts::font_files()` and `sysfonts::font_paths()` interactively. The output I get is sensible and nothing breaks.
```
> sysfonts::font_paths()
[1] "/Library/Fonts"                  "/Users/juliasilge/Library/Fonts"
```

When I use the reprex package and run the same code, I get the error:
```
sysfonts::font_paths()
#> Error: .onLoad failed in loadNamespace() for 'sysfonts', details:
#>   call: dyn.load(file, DLLpath = DLLpath, ...)
#>   error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so':
#>   dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
#>   Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so
#>   Reason: image not found
```
I am not 100% sure everything that [reprex](https://github.com/tidyverse/reprex) does, but it seems like something is going on with the user or permissions or session or something? And the installation process is obviously more like reprex than like whatever I am doing interactively.

**Comment by angela-li** [comment]
I am having exactly the same problem as described above, with the same error messages. Would appreciate any support you could provide with regards to this issue.

**Comment by GuangchuangYu** [comment]
do you have [XQuartz](https://www.xquartz.org/) installed?

**Comment by raynamharris** [comment]
Installing XQuartz solved the problem for me! Thanks @GuangchuangYu

**Comment by rcorty** [comment]
Installing XQuartz did not solve the problem for me

**Comment by rcorty** [comment]
This is addressed in https://github.com/GuangchuangYu/hexSticker/pull/56.

**Comment by IyarLin** [comment]
Installing XQuartz worked for me too. Thanks @GuangchuangYu !
