### ISSUE TITLE
how to increase resolution?

### ISSUE THREAD

**Issue by maelle** [GuangchuangYu/hexSticker#37]
would it be possible to increase resolution, maybe via exposing the `dpi` argument of `ggsave`?

cc @hturner

**Comment by GuangchuangYu** [comment]
now supported.

**Comment by maelle** [comment]
Thanks! Could you please provide an example? I was used to using `sticker` directly. My first try was a failure.

**Comment by GuangchuangYu** [comment]
pls update to latest version and use *e.g.* `sticker(dpi=300)`.

**Comment by maelle** [comment]
Many thanks @GuangchuangYu! 😺
