### ISSUE TITLE
Crop image file within shape of hexagon

### ISSUE THREAD

**Issue by peterdesmet** [GuangchuangYu/hexSticker#39]
Is there a way to crop a (larger) image file within the shape of the hexagon? Currently, a larger image file is put on top of the border (extending beyond the shape of the hexagon), rather than the border being the top layer, cropping the image.

E.g. @strengejacke, I was wondering how you created this logo:

![ggeffects](https://raw.githubusercontent.com/strengejacke/ggeffects/master/man/figures/logo.png)

**Comment by strengejacke** [comment]
This was actually an image manipulation with [paint.net](https://www.getpaint.net/), based on a sticker I created with the hexSticker package.

**Comment by rcorty** [comment]
hacky solution to this is to put a white trialge in each corner.  See https://github.com/GuangchuangYu/hexSticker/pull/56.

**Comment by AndyBunn** [comment]
I'd also love to see this functionality straight from {hexSticker::sticker}

**Comment by GuangchuangYu** [comment]
`white_around_sticker=TRUE` works for this purpose.

**Comment by guyabel** [comment]
In case anyone came here (like me) wanting a transparent background rather than white, you can use magick to convert the white to transparent:

```
library(magick)
p <- image_read("https://raw.githubusercontent.com/GuangchuangYu/hexSticker/master/inst/figures/baseplot.png")
pp <- p %>%
  image_fill(color = "transparent", refcolor = "white", fuzz = 4, point = "+1+1") %>%
  image_fill(color = "transparent", refcolor = "white", fuzz = 4, point = "+517+1") %>%
  image_fill(color = "transparent", refcolor = "white", fuzz = 4, point = "+1+599") %>%
  image_fill(color = "transparent", refcolor = "white", fuzz = 4, point = "+517+599")
image_write(image = pp, path = "hex_transp.png")
file.show("hex_transp.png")
```

**Comment by danielvartan** [comment]
An easier way to crop the hex logo is using the [`cropcircles`](https://github.com/doehm/cropcircles) package.

```r
library(cropcircles)

hex_crop(
  images = "image.png",
  to = "image-cropped.png"
)
```
