### ISSUE TITLE
Feature request: display= option to show the generated sticker onscreen

### ISSUE THREAD

**Issue by friendly** [GuangchuangYu/hexSticker#51]
`sticker()` should have an option, `display=TRUE/FALSE` where `TRUE` opens the created image for viewing onscreen. At present, my workaround is to use

    sticker(..., filename="mysticker.png")
    img <- png::readPNG("mysticker.png")
    grid::grid.raster(img)

But this only works in R console, not in RStudio, because it doesn't create a plot window that can be manipulated.

**Comment by GuangchuangYu** [comment]
try:

```
p <- sticker(..., filename = "xxx.png")
print(p)
```

**Comment by friendly** [comment]
thanks.  This is probably suitable for a preview; however, `print(p)` renders the border in a thin line, compared to `grid.raster()` or opening the image outside R.
