### ISSUE TITLE
update R version 3.5.3, and package ‘gridGraphics’ is not available 

### ISSUE THREAD

**Issue by JaneLiu0617** [GuangchuangYu/hexSticker#61]
Hi, I just tried to use the package while it seemed that gridGraphics package no longer available. 
And I kept got the error:
Error: package or namespace load failed for ‘hexSticker’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘gridGraphics’
Does anyone have some solution?

**Comment by loleg** [comment]
+1. On installation the error looks like this:
```
ERROR: dependency ‘gridGraphics’ is not available for package ‘ggplotify’
* removing ‘/home/oleg/R/x86_64-redhat-linux-gnu-library/3.5/ggplotify’
Warning in install.packages :
  installation of package ‘ggplotify’ had non-zero exit status
ERROR: dependencies ‘ggplotify’, ‘magick’ are not available for package ‘ggimage’
```

**Comment by GuangchuangYu** [comment]
<https://github.com/GuangchuangYu/hexSticker/blob/master/README.md#imagemagick>

**Comment by JaneLiu0617** [comment]
While I think I already install ImageMagick, and typed below code in an Command Prompt window:

magick logo: logo.gif
magick identify logo.gif
magick logo.gif win:

After all that, it still could not install gridGraphics
