### ISSUE TITLE
gradient/spotlight

### ISSUE THREAD

**Issue by sgibb** [GuangchuangYu/hexSticker#7]
All the handcrafted  (made with Illustrater) stickers at https://github.com/Bioconductor/BiocStickers have a colour gradient for the background colour. Would it be possible to add this to `hexSticker` as well?

**Comment by jotsetung** [comment]
Alternative approach: use a spotlight. I played a little bit around and found the following solution:
```r
library(hexSticker)
library(ggplot2)
library(lattice)
library(grid)
library(hexbin)

p <- ggplot(aes(x = mpg, y = wt), data = mtcars) + geom_point()
## Add highlight:
set.seed(123)
vals_x <- rnorm(500000, sd = 2, mean = 0)
vals_y <- rnorm(500000, sd = 2, mean = 0)
whiteTrans <- function(n) {
    rgb(r = rep(1, n), g = rep(1, n), b = rep(1, n),
        alpha = seq(0, 0.4, length.out = n))
}
hgl <- hexbinplot(vals_x ~ vals_y, colramp = whiteTrans, colorkey = FALSE,
                  bty = "n", scales = list(draw = FALSE), xlab = "", ylab = "",
                  border = NA, par.settings = list(axis.line = list(col = NA)))
## Combine the plots; have to adjust x, y, width and height to the mtcars data
p <- p + geom_subview(hgl, x = 21.5, y = 2.2,
                      width = 50, height = 50) +
    theme_void() + theme_transparent()
print(p)
sticker(p, package="hexSticker", p_size=8, s_x=1, s_y=.75, s_width=1.3, s_height=1,
        filename="ggplot2_highlight.png")

```

it involves a little try and error but looks not too bad I think:

![ggplot2_highlight](https://cloud.githubusercontent.com/assets/5506112/24564731/390a0f6a-1653-11e7-90d6-27b464128fb8.png)

Somehow makes sense to have hexagon-shaped highlights in a hexagonal image.

**Comment by jotsetung** [comment]
@GuangchuangYu , do you think it could be included into `hexSticker`? See related https://github.com/Bioconductor/BiocStickers/issues/27

**Comment by GuangchuangYu** [comment]
```
require(ggplot2)
require(hexSticker)
p <- ggplot(aes(x = mpg, y = wt), data = mtcars) + geom_point() + theme_void() + theme_transparent()
sticker(p, package="hexSticker", p_size=8, s_x=1, s_y=.75, s_width=1.3, s_height=1, spotlight=T,  filename="ggplot2_highlight.png")
```

![ggplot2_highlight](https://cloud.githubusercontent.com/assets/626539/24691705/b3b45312-1a07-11e7-9b67-a826e9bfcc8f.png)


By default, `spotlight=FALSE`. If we set `spotlight=TRUE`, it will be added and parameters, `l_x`, `l_y`, `l_width` and `l_height`, will work for the `spotlight`.

see <https://github.com/GuangchuangYu/hexSticker/commit/5a442e7e148db88cdb5a235fc32ba4b23686180a>.

**Comment by GuangchuangYu** [comment]
done!

![ggplot2_highlight](https://cloud.githubusercontent.com/assets/626539/24693152/d09220c0-1a0e-11e7-876c-4a609e13290c.png)

**Comment by GuangchuangYu** [comment]
@jotsetung actually, you can arrange layers after the sticker was created.

```r
pg <- sticker(p, package="hexSticker", p_size=8, 
            s_x=1, s_y=.75, s_width=1.3, s_height=1, 
            spotlight=T,  filename="ggplot2_highlight.png")
pg$layers = pg$layers[c(1, 3, 2, 4)]
save_sticker('ggplot2_highlight2.png', pg)
```

Then `ggplot2_highlight2.png` will be the first version.

**Comment by jotsetung** [comment]
Just a minor suggestion @GuangchuangYu : could you please add a parameter to specify the alpha/transparency of the spotlight?

**Comment by GuangchuangYu** [comment]
@jotsetung you mean the `0.4` in <https://github.com/GuangchuangYu/hexSticker/blob/master/R/sticker.R#L78> ?

**Comment by jotsetung** [comment]
yes, right, the max alpha.

**Comment by GuangchuangYu** [comment]
already added, <https://github.com/GuangchuangYu/hexSticker/commit/bb722a32f338d6f59b3efed9bd3f706f740b5112>.
