### ISSUE TITLE
add option for bold and italic fontface

### ISSUE THREAD

**Issue by MonkmanMH** [GuangchuangYu/hexSticker#72]
The package {showtext} allows the option for bold and italic faces of font families, through the parameter `fontface`. An example given in the {showtext} README:

```
annotate("text", 1, 0.9, label = 'Chinese for "Hello, world!"',
             family = "constan", fontface = "italic", size = 12)
```

It would be nice to have the same functionality in {hexSticker}. Thanks!

**Comment by loreabad6** [comment]
I was looking into this, and you can pass `fontface = "bold"` inside the `sticker()` function. But, this did not work for me with `"italic"`.

**Comment by GuangchuangYu** [comment]
the `p_fontface` parameter was introduced in v=0.4.9

**Comment by MonkmanMH** [comment]
Thank you!
