### ISSUE TITLE
sticker function fails: error in unit(rep(just$vjust), n)

### ISSUE THREAD

**Issue by mpadge** [GuangchuangYu/hexSticker#74]
Nice package, but unfortunately, I get this current fail (using your example code from the `sticker` fn):
``` r
library(ggplot2)
library(hexSticker)
packageVersion("hexSticker")
#> [1] '0.4.6'
p <- ggplot(aes(x = mpg, y = wt), data = mtcars) + geom_point()
p <- p + theme_void() + theme_transparent()
sticker(p, package="hexSticker")
#> Error in unit(rep(just$vjust, n), "npc") :
#> 'x' and 'units' must have length > 0
```

<sup>Created on 2019-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

A fix would be much appreciated!

**Comment by GuangchuangYu** [comment]
cannot reproduce the issue.

![image](https://user-images.githubusercontent.com/626539/66263878-af5fb180-e82c-11e9-910a-31bd99baa4f6.png)

**Comment by mpadge** [comment]
Yeah, you're right, sorry about that. I have a default theme set up in my `.Rprofile` that sets some of the same parameters as yours, but in different units. A clash then arises when you try to set up your `theme_transparent()` in different units. My fault, not yours. Thanks!
