### ISSUE TITLE
Greek letters in package name?

### ISSUE THREAD

**Issue by tati-micheletti** [GuangchuangYu/hexSticker#77]
Hey, first of all, thanks for the package. :)
I have been trying to add a greek letter to the package name, but it doesn't work. This is what I have tried:
```
library(ggplot2)
p <- ggplot(aes(x = mpg, y = wt), data = mtcars) + geom_point()
p <- p + theme_void() + theme_transparent()
sticker(p, package = "hexSticker~lambda", parse = TRUE)
sticker(p, package = "lambda", parse = TRUE)
```
Any advice? :) thanks!!

**Comment by GuangchuangYu** [comment]
The default font family doesn't support greek letter, please try to use different font family, such as:

```
sticker(p, package = "hexSticker~lambda", p_family="Sans", parse = TRUE)
```

**Comment by tati-micheletti** [comment]
Thanks for the email!

Any chances it's possible to combine 2 families of letters in the title? I
need to keep the consistency of the letters fonts of the other ones I'm
developing... :)

Thanks!!

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/66903436-0e93a200-f035-11e9-97fd-b62ce7a2d6ff.png)

**Comment by tati-micheletti** [comment]
You are awesome!! Thanks! :)
