### ISSUE TITLE
Is it possible to upload an existing png file from my local server to a sticker?

### ISSUE THREAD

**Issue by j-harbin** [GuangchuangYu/hexSticker#89]
Hi there,

I am new to using this package! I was wondering if there is a command to upload a png file from my local server to a sticker?

Thanks in advance

**Comment by j-harbin** [comment]
To provide further detail to this issue:

When I use the code, similar to the example for 'image file'

```
imgurl <- system.file("argoFloatsLogo.png", package="hexSticker")
sticker(imgurl, package="hexSticker", p_size=20, s_x=1, s_y=.75, s_width=.6,
        filename="inst/figures/imgfile.png")
```

I receive the following error:

```

Error in grDevices::png(..., res = dpi, units = "in") : 
  unable to start png() device
In addition: Warning messages:
1: In grDevices::png(..., res = dpi, units = "in") :
  unable to open file 'inst/figures/imgfile.png' for writing
2: In grDevices::png(..., res = dpi, units = "in") : opening device failed

```

Thank you for your help!

**Comment by GuangchuangYu** [comment]
the command is wrong.
```
imgurl <- system.file("argoFloatsLogo.png", package="hexSticker")
```

just use:
``
imgurl <- remote_url__or__file_path_in_your_system
```

**Comment by j-harbin** [comment]
Hi there,

I tried that as well. When I use the following code:

```
imgurl <- "C:/Users/harbinj/Documents/GitHub/argoFloats/sandbox/jlh/02_Logo/argoFloatsLogo.png"
sticker(imgurl, package="argoFloats", p_size=20, s_x=1, s_y=.75, s_width=.6,
        filename="inst/figures/imgfile.png")
```

And I receive the following error:

```
Error in grDevices::png(..., res = dpi, units = "in") : 
  unable to start png() device
In addition: Warning messages:
1: In grDevices::png(..., res = dpi, units = "in") :
  unable to open file 'inst/figures/imgfile.png' for writing
2: In grDevices::png(..., res = dpi, units = "in") : opening device failed
```

Thanks again!

**Comment by GuangchuangYu** [comment]
are you kidding me?

```
filename="inst/figures/imgfile.png")
```

there is no `inst/figures` folder in your current working directory.

1. don't just copy paste without looking at the code.
2. read the error before posting.

**Comment by j-harbin** [comment]
Hi there,

My apologies, I relatively new to R and still learning. Thank you for pointing that out, the code now works for me.
