### ISSUE TITLE
url at the lower border of the sticker

### ISSUE THREAD

**Issue by sgibb** [GuangchuangYu/hexSticker#9]
Would it be possible to put an URL at the lower right bottom of the sticker, e.g. www.bioconductor.org

![Biostrings sticker](https://raw.githubusercontent.com/Bioconductor/BiocStickers/master/Biostrings/Biostrings.png)

**Comment by GuangchuangYu** [comment]
done in <https://github.com/GuangchuangYu/hexSticker/commit/0886c01686908866be34079a82700a722017873a>.


```r
sticker(p, package="hexSticker", p_size=8, s_x=1, s_y=.75, s_width=1.3, s_height=1, url="www.bioconductor.org", filename="hex_url.png")
```

![hex_url](https://cloud.githubusercontent.com/assets/626539/25163012/90d81e08-24f9-11e7-9271-63ea005a3cde.png)

**Comment by sgibb** [comment]
great, thanks!

**Comment by Bohdan-Khomtchouk** [comment]
@sgibb Can you please upload your src code for the Biostrings sticker?  I ask because that is a *ridiculously* awesome looking design, I **absolutely** love it.  Cheers!

**Comment by sgibb** [comment]
@Bohdan-Khomtchouk I also really like the design of the Biostrings sticker but I am not the author. The maintainer is @Robbie90. Maybe he could give you access to the src.

You could find some files here: https://github.com/Bioconductor/BiocStickers/tree/master/Biostrings

**Comment by Robbie90** [comment]
@Bohdan-Khomtchouk really happy you like the design :) Unfortunately there is no R code behind that sticker since it was done entirely in Illustrator. However, you can download the PDF file at https://github.com/Bioconductor/BiocStickers/blob/master/Biostrings/Biostrings.pdf and open it in Inkscape to play with it.
