### ISSUE TITLE
Specify sticker dimensions

### ISSUE THREAD

**Issue by rafapereirabr** [GuangchuangYu/hexSticker#91]
Hi @GuangchuangYu. The `sticker` function currently has lots of arguments to  tweak the size of subplot and package name. However, I couldn't find an argument to specify the sicker dimensions. How can one set the sticker dimensions to 181x209 as a png ? 

ps. Thanks for the  hexSticker package!

**Comment by rafapereirabr** [comment]
Perhaps you could include the a `sticker_width` argument that would be passed to `save_sticker` >> `ggsave`  while keeping a predefined width x height ratio

**Comment by GuangchuangYu** [comment]
you can use `ggsave()` and specify width and height of the sticker.
