### ISSUE TITLE
[Suggestion] Code for preview hexSticker.

### ISSUE THREAD

**Issue by jhk0530** [GuangchuangYu/hexSticker#92]
Hi, 
I used this hexSticker package a lot for my works, Thanks a lot. :heart:

However, while I create hexsticker, I use `plot` or `print` function to preview ( #51 ) and it's little bit different between image of `Plots (of Rstudio)` and real generated image like `baseplot.png`. 
and it's repetitive job to control size or location for hexsticker.

and I found alternative approach to see preview image as created.
use `imager` package to load created image file and plot it to `Plots (of Rstudio)`

------

Here's example code for given examples in README.

* This code is I used to create preview image.

```R
library(hexSticker)

s<- sticker(~plot(cars, cex=.5, cex.axis=.5, mgp=c(0,.3,0), xlab="", ylab=""),
        package="hexSticker", p_size=20, s_x=.8, s_y=.6, s_width=1.4, s_height=1.2,
        filename="temp.png")
print(s) # or plot(s)
```
which will show this image

<img src ='https://user-images.githubusercontent.com/6457691/78001308-7b46f280-7370-11ea-92e7-3c72c3a1b125.png' width = '300'>

```R
library(hexSticker)
library(imager) 
sticker(~plot(cars, cex=.5, cex.axis=.5, mgp=c(0,.3,0), xlab="", ylab=""),
        package="hexSticker", p_size=20, s_x=.8, s_y=.6, s_width=1.4, s_height=1.2,
        filename="temp.png")
plot(imager::load.image('temp.png'), axes = FALSE)
```

and this will show below image which is same for created image.

<img src='https://user-images.githubusercontent.com/6457691/78001253-65393200-7370-11ea-8022-f9c8944a96d5.png' width = '300'>

------
I think this approach can be applied to change in README file easily.
but I'm not sure about how to implement inside package.

Regards,

**Comment by GuangchuangYu** [comment]
```r
library(hexSticker)

s<- sticker(~plot(cars, cex=.5, cex.axis=.5, mgp=c(0,.3,0), xlab="", ylab=""),
        package="hexSticker", p_size=20, s_x=.8, s_y=.6, s_width=1.4, s_height=1.2,
        filename="temp.png")
plot(s) ## <----- try this :)
```

**Comment by jhk0530** [comment]
Thank you for kind response 👍
