### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by damianooldoni** [GuangchuangYu/hexSticker#96]
Hi, 

though I am not a native speaking English, I would like to let you know about a possible typo in the README:

> The sticker() will generate a figure **specify** by the filename parameter.

Shouldn't it be: 
_The sticker() will generate a figure **specified** by the filename parameter._ ?

Thanks for this very interesting package!
Damiano

**Comment by GuangchuangYu** [comment]
thanks.
